docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Storage:
        - Adapters: storage/adapter.md
        - Capabilities: storage/capabilities.md
        - Plugins: storage/plugin.md
    - "Cache Patterns":
        - Introduction: pattern/intro.md
        - CallbackCache: pattern/callback-cache.md
        - ClassCache: pattern/class-cache.md
        - ObjectCache: pattern/object-cache.md
        - OutputCache: pattern/output-cache.md
        - CaptureCache: pattern/capture-cache.md
    - PSR-6: psr6.md
site_name: zend-cache
site_description: Zend\Cache
repo_url: 'https://github.com/zendframework/zend-cache'
copyright: 'Copyright (c) 2005-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
